config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  root 'homes#top'

  get 'maps/index'
  get 'home/about' => 'homes#about'
  post 'home/guest_sign_in', to: 'homes#new_guest'

  resources :maps, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :recruitments do
    collection do
      get 'search'
      get 'text_search'
    end
  resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
    member do
      get 'mypage_show'
      get 'mypage_edit'
      patch 'mypage_update'
      get 'out'
      patch 'quit'
      get 'following'
      get 'followers'
    end
  end
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord

  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :user

  #いいね 機能
  def liked_by(user)
    Like.find_by(user_id: user.id, recruitment_id: id)
  end

  # 検索機能
  def self.search(search)
    search ? where('title LIKE ?', "%#{search}%") : all
  end

  # 通知機能
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visiter_id = ? and visited_id = ? and recruitment_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        recruitment_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recruitment = Recruitment.new
  end

  def index
    @recruitments = Recruitment.all.page(params[:page]).per(6)
  end

  def show
    @recruitment = Recruitment.find(params[:id])

    # DM機能
    @userId = @recruitment.user.id

    @currentUserEntry = Entry.where(user_id: current_user.id)

    @userEntry = Entry.where(user_id: @userId)

    unless @userId == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def create
    @recruitment = Recruitment.new(recruitment_params)
    @recruitment.user_id = current_user.id
    @recruitment.save
    redirect_to recruitments_path
  end

  def destroy
    recruitment = Recruitment.find(params[:id])
    recruitment.destroy
    redirect_to recruitments_path
  end

  def edit
    @recruitment = Recruitment.find(params[:id])
  end

  def update
    @recruitment = Recruitment.find(params[:id])
    if @recruitment.update(recruitment_params)
      redirect_to recruitments_path
    else
      render :edit
    end
  end

  def search
    place_area_ids = Recruitment.where("place_area LIKE (?)", "#{params[:place_area]}").pluck(:id)
    sports_genre_ids = Recruitment.where("sports_genre LIKE (?)", "#{params[:sports_genre]}").pluck(:id)
    @result_searched = Recruitment.where("id IN (?) or id IN (?)", place_area_ids, sports_genre_ids).page(params[:page]).per(6)
  end

  def text_search
    @recruitments = Recruitment.all.search(params[:search]).page(params[:page]).per(5)
  end

  private

  def recruitment_params
    params.require(:recruitment).permit(:title, :event_date, :place, :price, :recruitment_introduction, :place_area, :sports_genre)
  end

  def correct_user
      user = Recruitment.find(params[:user_id])
      redirect_to root_url if current_user != user
  end


end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/views/recruitments/_like.html.erb
<%= link_to(recruitment_likes_path(recruitment), method: :POST, remote: true, class: "like") do %>
  <i class="fa fa-heart" aria-hidden="true"></i>いいね数：<%= recruitment.likes.count %>
<% end %>

app/views/recruitments/_like_form.html.erb
      <strong id="<%= recruitment.id.to_s %>" class="float-right" >
        <% if recruitment.liked_by(current_user).present? %>
          <%= render "unlike", recruitment: recruitment %>
        <% else %>
          <%= render "like", recruitment: recruitment %>
        <% end %>
      </strong>

app/views/recruitments/_unlike.html.erb
<%= link_to(recruitment_like_path(recruitment.id, recruitment.liked_by(current_user)), method: :DELETE, remote: true, class: "unlike") do %>
  <i class="fa fa-heart" aria-hidden="true"></i>いいね数：<%= recruitment.likes.count %>
<% end %>

app/views/recruitments/edit.html.erb
<%= form_with model:@recruitment,url: recruitment_path, local:true do  |f| %>

  <div class="my-3 p-3 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0"></h6>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray" style="width: 200px;">
          <strong class="d-block text-gray-dark">タイトル</strong>
          <strong class="d-block text-gray-dark mx-auto row" style="width: 200px;"><%= f.text_field :title, autofocus: true, class: "title", size: "80x10" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">募集者</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
            <%= attachment_image_tag(current_user, :profile_image, :fill, 50, 50, class:"bd-placeholder-img mr-2 rounded", fallback: "no-image-icon.jpg") %>
            <%= current_user.name %>
          </strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">スポーツジャンル</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
            <%= f.select :sports_genre, [["フットサル", "フットサル"], ["野球", "野球"] ,["バスケ","バスケ" ], ["テニス", "テニス"]],prompt: "スポーツジャンルを選択してください", class: "sports_genre" %>
          </strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">開催エリア</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
            <%= f.select :place_area, [ ["北海道","北海道"], ["青森", "青森"], ["岩手", "岩手"] ,["宮城","宮城" ], ["秋田", "秋田"], ["山形", "山形"],["福島", "福島"],["茨城", "茨城"],["栃木", "栃木"],["群馬", "群馬"],["埼玉", "埼玉"],["千葉", "千葉"],["東京", "東京"],["神奈川", "神奈川"],["新潟", "新潟"],["富山", "富山"],["石川", "石川"],["福井", "福井"],["山梨", "山梨"],["長野", "長野"],["岐阜", "岐阜"],["静岡", "静岡"],["愛知", "愛知"],["三重", "三重"],["滋賀", "滋賀"],["京都", "京都"],["大阪", "大阪"],["兵庫", "兵庫"],["奈良", "奈良"],["和歌山", "和歌山"],["鳥取", "鳥取"],["島根", "島根"],["岡山", "岡山"],["広島", "広島"],["山口", "山口"],["徳島", "徳島"],["香川", "香川"],["愛媛", "愛媛"],["高知", "高知"],["福岡", "福岡"],["佐賀", "佐賀"],["長崎", "長崎"],["熊本", "熊本"],["大分", "大分"],["宮崎", "宮崎"],["鹿児島", "鹿児島"],["沖縄", "沖縄"]],prompt: "県を選択してください", class: "place_area" %>
          </strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">開催日</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.datetime_field :event_date, autofocus: true, class: "event_date"%></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">場所</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.text_field :place, autofocus: true, class: "place", size: "80x10" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">値段</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.text_field :price, autofocus: true, class: "price", size: "80x10" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">本文</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.text_area :recruitment_introduction, autofocus: true, class: "recruitment_introduction", size: "80x10" %></strong>
        </p>
      </div>

  <div class="row">
      <%= f.submit "募集を保存する",class: "btn btn-primary  offset-md-5 col-md-2 " %>
  </div>

<% end %>

app/views/recruitments/index.html.erb
<%= form_tag(search_recruitments_path, method: "get" ,class:'text-center') do %>
 <%= select_tag "place_area",options_for_select([["北海道","北海道"], ["青森", "青森"], ["岩手", "岩手"] ,["宮城","宮城" ], ["秋田", "秋田"], ["山形", "山形"],["福島", "福島"],["茨城", "茨城"],["栃木", "栃木"],["群馬", "群馬"],["埼玉", "埼玉"],["千葉", "千葉"],["東京", "東京"],["神奈川", "神奈川"],["新潟", "新潟"],["富山", "富山"],["石川", "石川"],["福井", "福井"],["山梨", "山梨"],["長野", "長野"],["岐阜", "岐阜"],["静岡", "静岡"],["愛知", "愛知"],["三重", "三重"],["滋賀", "滋賀"],["京都", "京都"],["大阪", "大阪"],["兵庫", "兵庫"],["奈良", "奈良"],["和歌山", "和歌山"],["鳥取", "鳥取"],["島根", "島根"],["岡山", "岡山"],["広島", "広島"],["山口", "山口"],["徳島", "徳島"],["香川", "香川"],["愛媛", "愛媛"],["高知", "高知"],["福岡", "福岡"],["佐賀", "佐賀"],["長崎", "長崎"],["熊本", "熊本"],["大分", "大分"],["宮崎", "宮崎"],["鹿児島", "鹿児島"],["沖縄", "沖縄"]]) %>
 <%= select_tag "sports_genre", options_for_select([["フットサル", "フットサル"], ["野球", "野球"] ,["バスケ","バスケ" ], ["テニス", "テニス"]]) %>
 <%= submit_tag "検索" %>
<% end %>

<main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">募集一覧</h6>
      <% @recruitments.each do |recruitment| %>
        <div class="media text-muted pt-3">
          <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32">
            <%= attachment_image_tag(recruitment.user, :profile_image, :fill, 32, 32, class: "rounded-circle", fallback: "no-image-icon.jpg") %>
          </svg>
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">タイトル</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.title %></strong>
            <strong class="d-block text-gray-dark">開催日</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.event_date %></strong>
            <strong class="d-block text-gray-dark">開催場所</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.place %></strong>
            <strong class="d-block text-gray-dark">値段</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.price %></strong>
            <% if recruitment.user.id == current_user.id %>
              <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
                <%= link_to "詳細", recruitment_path(recruitment), class: "show" %>
                <%= link_to '編集', edit_recruitment_path(recruitment), class: "edit text-success"%>
                <%= link_to '削除', recruitment_path(recruitment), class: "destroy text-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %>
              </strong>
            <% else %>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
              <%= link_to "詳細", recruitment_path(recruitment), class: "show" %>
            </strong>
            <% end %>
            <%= render 'like_form', recruitment: recruitment %>
          </p>
        </div>
      <% end %>
      <small class="d-block mt-3">
        <%= paginate @recruitments %>
      </small>
    </div>
    <%= link_to "募集情報を作成する", new_recruitment_path, class: "btn btn-success offset-md-5 col-md-2" %>
</main>

app/views/recruitments/search.html.erb
<main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">募集一覧</h6>
      <% @result_searched.each do |result_searched| %>
        <div class="media text-muted pt-3">
          <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32">
            <%= attachment_image_tag(result_searched.user, :profile_image, :fill, 32, 32, class: "rounded-circle", fallback: "no-image-icon.jpg") %>
          </svg>
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">タイトル</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= result_searched.title %></strong>
            <strong class="d-block text-gray-dark">開催日</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= result_searched.event_date %></strong>
            <strong class="d-block text-gray-dark">開催場所</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= result_searched.place %></strong>
            <strong class="d-block text-gray-dark">値段</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= result_searched.price %></strong>
            <% if result_searched.user.id == current_user.id %>
              <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
                <%= link_to "詳細", recruitment_path(result_searched), class: "show" %>
                <%= link_to '編集', edit_recruitment_path(result_searched), class: "edit text-success"%>
                <%= link_to '削除', recruitment_path(result_searched), class: "destroy text-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %>
              </strong>
            <% else %>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
              <%= link_to "詳細", recruitment_path(result_searched), class: "show" %>
            </strong>
            <% end %>
          </p>
        </div>
      <% end %>
      <small class="d-block text-right mt-3">
        <%= paginate @result_searched %>
      </small>
    </div>
    <%= link_to "募集情報を作成する", new_recruitment_path, class: "btn btn-success offset-md-5 col-md-2" %>
</main>

app/views/recruitments/show.html.erb
  <div class="my-3 p-3 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0"></h6>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray" style="width: 200px;">
          <strong class="d-block text-gray-dark">タイトル</strong>
          <strong class="d-block text-gray-dark mx-auto row" style="width: 200px;"><%= @recruitment.title %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">募集者</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
            <%= attachment_image_tag(@recruitment.user, :profile_image, :fill, 50, 50, class: "rounded-circle", fallback: "no-image-icon.jpg") %>
            <%= @recruitment.user.name %>
          </strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">開催日</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @recruitment.event_date %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">場所</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @recruitment.place %></strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= link_to "Googlemapへ", maps_path, class: "googlemap" %></strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">値段</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @recruitment.price %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">本文</strong>
          <strong class="d-block text-gray-dark mx-auto recruitment_introduction" style="width: 200px;"><%= @recruitment.recruitment_introduction %></strong>
        </p>
      </div>

      <!--DM機能-->
      <% if @userId == current_user.id %>

      <% else %>
        <% if @isRoom == true %>
        <div class="row">
          <%= link_to 'チャット画面へ', room_path(@roomId), class: "btn btn-warning  offset-md-5 col-md-2"%>
        </div>
        <% else %>
          <%= form_for @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, :value=> @userId %>
            <% end %>
            <%= f.submit "チャット画面へ", class:"btn btn-warning  offset-md-5 col-md-2" %>
          <% end %>
        <% end %>
      <% end %>

app/views/recruitments/text_search.html.erb
<%= form_tag(search_recruitments_path, method: "get" ,class:'text-center') do %>
 <%= select_tag "place_area",options_for_select([["北海道","北海道"], ["青森", "青森"], ["岩手", "岩手"] ,["宮城","宮城" ], ["秋田", "秋田"], ["山形", "山形"],["福島", "福島"],["茨城", "茨城"],["栃木", "栃木"],["群馬", "群馬"],["埼玉", "埼玉"],["千葉", "千葉"],["東京", "東京"],["神奈川", "神奈川"],["新潟", "新潟"],["富山", "富山"],["石川", "石川"],["福井", "福井"],["山梨", "山梨"],["長野", "長野"],["岐阜", "岐阜"],["静岡", "静岡"],["愛知", "愛知"],["三重", "三重"],["滋賀", "滋賀"],["京都", "京都"],["大阪", "大阪"],["兵庫", "兵庫"],["奈良", "奈良"],["和歌山", "和歌山"],["鳥取", "鳥取"],["島根", "島根"],["岡山", "岡山"],["広島", "広島"],["山口", "山口"],["徳島", "徳島"],["香川", "香川"],["愛媛", "愛媛"],["高知", "高知"],["福岡", "福岡"],["佐賀", "佐賀"],["長崎", "長崎"],["熊本", "熊本"],["大分", "大分"],["宮崎", "宮崎"],["鹿児島", "鹿児島"],["沖縄", "沖縄"]]) %>
 <%= select_tag "sports_genre", options_for_select([["フットサル", "フットサル"], ["野球", "野球"] ,["バスケ","バスケ" ], ["テニス", "テニス"]]) %>
 <%= submit_tag "検索" %>
<% end %>


<main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
      <h6 class="border-bottom border-gray pb-2 mb-0">募集一覧</h6>
      <% @recruitments.each do |recruitment| %>
        <div class="media text-muted pt-3">
          <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32">
            <%= attachment_image_tag(recruitment.user, :profile_image, :fill, 32, 32, class: "rounded-circle", fallback: "no-image-icon.jpg") %>
          </svg>
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">タイトル</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.title %></strong>
            <strong class="d-block text-gray-dark">開催日</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.event_date %></strong>
            <strong class="d-block text-gray-dark">開催場所</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.place %></strong>
            <strong class="d-block text-gray-dark">値段</strong>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= recruitment.price %></strong>
            <% if recruitment.user.id == current_user.id %>
              <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
                <%= link_to "詳細", recruitment_path(recruitment), class: "show" %>
                <%= link_to '編集', edit_recruitment_path(recruitment), class: "edit text-success"%>
                <%= link_to '削除', recruitment_path(recruitment), class: "destroy text-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %>
              </strong>
            <% else %>
            <strong class="d-block text-gray-dark mx-auto" style="width: 200px;">
              <%= link_to "詳細", recruitment_path(recruitment), class: "show" %>
            </strong>
            <% end %>
          </p>
        </div>
      <% end %>
      <small class="d-block text-right mt-3">
        <a href="#"><%= paginate @recruitments %></a>
      </small>
    </div>
    <%= link_to "募集情報を作成する", new_recruitment_path, class: "btn btn-success offset-md-5 col-md-2" %>
</main>