config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  root 'homes#top'

  get 'maps/index'
  get 'home/about' => 'homes#about'
  post 'home/guest_sign_in', to: 'homes#new_guest'

  resources :maps, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :recruitments do
    collection do
      get 'search'
      get 'text_search'
    end
  resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
    member do
      get 'mypage_show'
      get 'mypage_edit'
      patch 'mypage_update'
      get 'out'
      patch 'quit'
      get 'following'
      get 'followers'
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope->{order(created_at: :desc)}

  belongs_to :recruitment, optional: true
  belongs_to :user, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    #current_userが受け取った通知
    @notifications = current_user.passive_notifications.page(params[:page]).per(8)
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    #通知を全削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
      @visiter = notification.visiter
      #notification.actionがfollowかlikeか
      case notification.action
        when "follow" then
          tag.a(notification.visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
        when "like" then
          tag.a(notification.visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:recruitment_path(notification.recruitment_id), style:"font-weight: bold;")+"にいいねしました"
      end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end

end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% recruitment = notification.recruitment %>

<div class="my-3 p-3 bg-white rounded shadow-sm">
  <%= link_to users_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill,100,100, format: "jpeg", fallback: "no_image.jpg", size: "50x50", class: "rounded-circle" %>
  <% end %>
  <%= notification_form(notification) %><span><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
</div>

app/views/notifications/index.html.erb
<h3 class="text-center">通知</h3>
    <%= link_to destroy_all_notifications_path, method: :delete do %>
        <h7 class="fa fa-trash">全削除</h7>
    <% end %>
    <hr>
<% if @notifications.exists? %>
    <div class="users-index">
        <%= render @notifications %>
    </div>
<% else %>
    <p>通知はありません</p>
<% end %>