config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  root 'homes#top'

  get 'maps/index'
  get 'home/about' => 'homes#about'
  post 'home/guest_sign_in', to: 'homes#new_guest'

  resources :maps, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :recruitments do
    collection do
      get 'search'
      get 'text_search'
    end
  resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
    member do
      get 'mypage_show'
      get 'mypage_edit'
      patch 'mypage_update'
      get 'out'
      patch 'quit'
      get 'following'
      get 'followers'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]



  attachment :profile_image

  has_many :likes
  has_many :recruitments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :notifications, dependent: :destroy

  #フォロー機能
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  validates :name, :email, :postal_code, :address, :gender, :age, :favorites_sports, presence: :true


  #フォローしているかを確認
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローする
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外す
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
  end

   def self.with_sns_data(auth, snscredential)
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
      end
      return {user: user}
   end

   def self.find_oauth(auth)
      uid = auth.uid
      provider = auth.provider
      snscredential = SnsCredential.where(uid: uid, provider: provider).first
      if snscredential.present?
        user = with_sns_data(auth, snscredential)[:user]
        sns = snscredential
      else
        user = without_sns_data(auth)[:user]
        sns = without_sns_data(auth)[:sns]
      end
      return { user: user ,sns: sns}
   end

  # 通知機能メソッド
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to root_path and return
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:mypage_edit, :mypage_update]


  #ユーザーの一覧
  def index
    @users = User.all.page(params[:page]).per(6)
  end

  #ユーザーの詳細
  def show
    @user = User.find(params[:id])
    @following_users = @user.following
    @followers_users = @user.followers
  end

  #マイページの詳細
  def mypage_show
  end

  #マイページの編集画面
  def mypage_edit
  end

  #マイページの編集の保存
  def mypage_update
    if current_user.update(user_params)
      redirect_to mypage_show_user_path
    else
      render "mypage_edit"
    end
  end

  #退会ボタン押下時
  def quit
  end

  #退会画面の表示
  def out
  end

  private

   def user_params
      params.require(:user).permit(:profile_image, :name, :email, :postal_code, :address, :gender, :age, :favorites_sports, :introduction)
   end

   def correct_user
      user = User.find(params[:id])
      redirect_to root_url if current_user != user
   end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<!-- フォローボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && user != current_user %>
  <div class = <%="follow_form" + user.id.to_s %>>
    <% if current_user.following?(user) %>
      <%= render "unfollow", user: user %>
    <% else %>
      <%= render "follow", user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- フォロー解除ボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationship_path(user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-danger" %>
<% end %>

app/views/users/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>アイコン</th>
      <th>名前</th>
      <th>性別</th>
      <th>年代</th>
      <th>スポーツ</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, class: "rounded-circle", fallback: "no-image-icon.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= user.gender %></td>
        <td><%= user.age %></td>
        <td><%= user.favorites_sports %></td>
        <td><%= render 'follow_form', user: user %></td>
        <td><%= link_to '詳細', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/users/mypage_edit.html.erb
<%= form_with model:current_user,url: mypage_update_user_path, local:true, method: :patch do  |f| %>

  <div class="my-3 p-3 bg-white rounded shadow-sm">

      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray" style="width: 200px;">
          <strong class="d-block text-gray-dark">アイコン</strong>
          <strong class="d-block text-gray-dark mx-auto row" style="width: 200px;"><%= f.attachment_field :profile_image, class: "rounded-circle" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray" style="width: 200px;">
          <strong class="d-block text-gray-dark">名前</strong>
          <strong class="d-block text-gray-dark mx-auto row" style="width: 200px;"><%= f.text_field :name, autofocus: true, class: "name" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">メールアドレス</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.email_field :email, autofocus: true, class: "email" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">郵便番号(ハイフンなし）</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.text_field :postal_code, autofocus: true, class: "postal_code" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">住所</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.text_field :address, autofocus: true, class: "address" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">年齢</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.select :age, [ ["10代","10代"], ["20代", "20代"], ["30代", "30代"] ,["40代","40代" ], ["50代", "50代"], ["60代", "60代"],["70代", "70代"],["その他", "その他"],["回答しない", "回答しない"]],prompt: "年齢を選択してください", class: "age" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">性別</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.select :gender, [ ["男","男"], ["女", "女"], ["その他", "その他"] ,["回答しない","回答しない" ]],prompt: "性別を選択してください", class: "gender" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">好きなスポーツ</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.select :favorites_sports, [ ["フットサル","フットサル"], ["野球", "野球"],["バスケ","バスケ" ] ,["テニス","テニス" ]],prompt: "スポーツを選択してください", class: "favorites_sports" %></strong>
        </p>
      </div>
      <div class="media text-muted pt-3">
        <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
        <p class="media-body pb-3 mb-0 small lh-125">
          <strong class="d-block text-gray-dark">自己紹介</strong>
          <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= f.text_area :introduction, autofocus: true, class: "introduction",size: "80x10" %></strong>
        </p>
      </div>
    </div>

  <div class="row">
      <%= f.submit "保存する",class: "btn btn-primary offset-md-5 col-md-2" %>
  </div>

<% end %>

app/views/users/mypage_show.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark text-right">フォロー数：<%= current_user.following.count %> フォロワー数：<%= current_user.followers.count %></strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= attachment_image_tag(current_user, :profile_image, :fill, 100, 100, class: "rounded-circle", fallback: "no-image-icon.jpg") %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">名前</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.name %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">メールアドレス</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.email %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">郵便番号(ハイフンなし）</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.postal_code %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">住所</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.address %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">年齢</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.gender %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">性別</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.age %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">好きなスポーツ</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.favorites_sports %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125">
        <strong class="d-block text-gray-dark">自己紹介</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= current_user.introduction %></strong>
      </p>
    </div>
  </div>

  <div>
    <%= link_to "編集する", mypage_edit_user_path, class: "btn btn-success offset-md-5 col-md-2" %>
  </div>

app/views/users/show.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark text-right">フォロー数：<%= @user.following.count %> フォロワー数：<%= @user.followers.count %></strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, class: "rounded-circle", fallback: "no-image-icon.jpg") %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">名前</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @user.name %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">年齢</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @user.gender %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">性別</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @user.age %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">好きなスポーツ</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @user.favorites_sports %></strong>
      </p>
    </div>
    <div class="media text-muted pt-3">
      <img data-src="holder.js/32x32?theme=thumb&amp;bg=e83e8c&amp;fg=e83e8c&amp;size=1" alt="" class="mr-2 rounded">
      <p class="media-body pb-3 mb-0 small lh-125">
        <strong class="d-block text-gray-dark">自己紹介</strong>
        <strong class="d-block text-gray-dark mx-auto" style="width: 200px;"><%= @user.introduction %></strong>
      </p>
    </div>
  </div>