config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  root 'homes#top'

  get 'maps/index'
  get 'home/about' => 'homes#about'
  post 'home/guest_sign_in', to: 'homes#new_guest'

  resources :maps, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :recruitments do
    collection do
      get 'search'
      get 'text_search'
    end
  resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
    member do
      get 'mypage_show'
      get 'mypage_edit'
      patch 'mypage_update'
      get 'out'
      patch 'quit'
      get 'following'
      get 'followers'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recruitment

  validates :user_id, uniqueness: { scope: :recruitment_id }

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope->{order(created_at: :desc)}

  belongs_to :recruitment, optional: true
  belongs_to :user, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord

  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :user

  #いいね 機能
  def liked_by(user)
    Like.find_by(user_id: user.id, recruitment_id: id)
  end

  # 検索機能
  def self.search(search)
    search ? where('title LIKE ?', "%#{search}%") : all
  end

  # 通知機能
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visiter_id = ? and visited_id = ? and recruitment_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        recruitment_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

    #自分をフォローしているユーザー
    belongs_to :follower, class_name: "User"
    #自分がフォローしているユーザー
    belongs_to :following, class_name: "User"

    validates :follower_id, presence: true
    validates :following_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

end
 

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]



  attachment :profile_image

  has_many :likes
  has_many :recruitments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :notifications, dependent: :destroy

  #フォロー機能
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy


  validates :name, :email, :postal_code, :address, :gender, :age, :favorites_sports, presence: :true


  #フォローしているかを確認
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローする
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外す
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
  end

   def self.with_sns_data(auth, snscredential)
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
      end
      return {user: user}
   end

   def self.find_oauth(auth)
      uid = auth.uid
      provider = auth.provider
      snscredential = SnsCredential.where(uid: uid, provider: provider).first
      if snscredential.present?
        user = with_sns_data(auth, snscredential)[:user]
        sns = snscredential
      else
        user = without_sns_data(auth)[:user]
        sns = without_sns_data(auth)[:sns]
      end
      return { user: user ,sns: sns}
   end

  # 通知機能メソッド
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストログイン"
      user.postal_code = "999999"
      user.address = "ゲストログイン"
      user.gender = "回答しない"
      user.age = "回答しない"
      user.favorites_sports = "フットサル"
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to recruitments_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
  <div class="fixed-bottom text-center">
    © SportsPark
  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <span class="navbar-brand">SportsPark</span>

  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "募集情報一覧", recruitments_path, class: "nav-link fa fa-calendar-check-o" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ユーザー一覧", users_path, class: "nav-link fa fa-users" %>
        </li>
        <li class="nav-item active">
          <%= link_to "チャット履歴へ", rooms_path, class: "nav-link fa fa-comments" %>
        </li>
        <li class="nav-item active">
          <%= link_to " マイページ", mypage_show_user_path(current_user), class: "nav-link fa fa-user-circle" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link fa fa-sign-out" %>
        </li>
        <% if unchecked_notifications.any? %>
          <i class="fa fa-circle"></i>
        <% end %>
        <li class="nav-item active">
          <%= link_to "通知", notifications_path, class: "nav-link fa fa-bell-o" %>
        </li>
      <% else %>
        <li class="nav-item text-light active">
          <%= link_to "Home", root_path, class: "nav-link fa fa-home " %>
        </li>
        <li class="nav-item text-light active">
          <%= link_to "About", home_about_path, class: "nav-link fa fa-book" %>
        </li>
        <li class="nav-item text-light active">
          <%= link_to " Sign_Up", new_user_registration_path, class: "nav-link fa fa-pencil" %>
        </li>
        <li class="nav-item text-light active">
          <%= link_to " Login", new_user_session_path, class: "nav-link fa fa-sign-in" %>
        </li>
      <% end %>
    </ul>


    <% if user_signed_in? %>
      <%= form_tag(text_search_recruitments_path, method: :get) do %>
        <%= text_field_tag :search, '' , placeholder: "募集情報のタイトル"	 %>
        <%= submit_tag '検索', name: nil%>
      <% end %>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>


<html>
  <head>
    <title>SportsPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="box">
    <div id="header">
      <%= render "layouts/header" %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <div id="footer">
      <%= render "layouts/footer" %>
    </div>
  </body>

</html>